/* tslint:disable */
/* eslint-disable */
/**
 * Shopping API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Family,
  Income,
} from '../models/index';
import {
    FamilyFromJSON,
    FamilyToJSON,
    IncomeFromJSON,
    IncomeToJSON,
} from '../models/index';

export interface FamiliesGetRequest {
    freeQuery?: string;
}

export interface FamiliesPostRequest {
    family?: Family;
}

export interface FamiliesPutRequest {
    family?: Array<Family>;
}

export interface IncomPostRequest {
    income?: Income;
}

/**
 * 
 */
export class DefaultApi extends runtime.BaseAPI {

    /**
     * Search families using a free query parameter 
     * Search families
     */
    async familiesGetRaw(requestParameters: FamiliesGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Family>>> {
        const queryParameters: any = {};

        if (requestParameters['freeQuery'] != null) {
            queryParameters['free-query'] = requestParameters['freeQuery'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/families`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(FamilyFromJSON));
    }

    /**
     * Search families using a free query parameter 
     * Search families
     */
    async familiesGet(requestParameters: FamiliesGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Family>> {
        const response = await this.familiesGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Add family\'s parameter 
     * Add family
     */
    async familiesPostRaw(requestParameters: FamiliesPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/families`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: FamilyToJSON(requestParameters['family']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Add family\'s parameter 
     * Add family
     */
    async familiesPost(requestParameters: FamiliesPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.familiesPostRaw(requestParameters, initOverrides);
    }

    /**
     * Add family\'s parameter 
     * Add family
     */
    async familiesPutRaw(requestParameters: FamiliesPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/families`;

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['family']!.map(FamilyToJSON),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Add family\'s parameter 
     * Add family
     */
    async familiesPut(requestParameters: FamiliesPutRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.familiesPutRaw(requestParameters, initOverrides);
    }

    /**
     * Get all incomes 
     * Get incomes
     */
    async incomGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Income>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/incom`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(IncomeFromJSON));
    }

    /**
     * Get all incomes 
     * Get incomes
     */
    async incomGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Income>> {
        const response = await this.incomGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Add income\'s parameter 
     * Add income
     */
    async incomPostRaw(requestParameters: IncomPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/incom`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: IncomeToJSON(requestParameters['income']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Add income\'s parameter 
     * Add income
     */
    async incomPost(requestParameters: IncomPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.incomPostRaw(requestParameters, initOverrides);
    }

}
