/* tslint:disable */
/* eslint-disable */
/**
 * Shopping API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Income,
} from '../models/index';
import {
    IncomeFromJSON,
    IncomeToJSON,
} from '../models/index';

export interface IncomPostRequest {
    income?: Income;
}

/**
 * 
 */
export class IncomeApi extends runtime.BaseAPI {

    /**
     * Get all incomes 
     * Get incomes
     */
    async incomGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Income>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/incom`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(IncomeFromJSON));
    }

    /**
     * Get all incomes 
     * Get incomes
     */
    async incomGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Income>> {
        const response = await this.incomGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Add income\'s parameter 
     * Add income
     */
    async incomPostRaw(requestParameters: IncomPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/incom`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: IncomeToJSON(requestParameters['income']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Add income\'s parameter 
     * Add income
     */
    async incomPost(requestParameters: IncomPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.incomPostRaw(requestParameters, initOverrides);
    }

}
