// This file is auto-generated by @hey-api/openapi-ts

export type { ClientOptions, Family, GetFamiliesData, GetFamiliesResponse, GetFamiliesResponses, GetIncomData, GetIncomResponse, GetIncomResponses, Income, PostFamiliesData, PostFamiliesResponses, PostIncomData, PostIncomResponses, PutFamiliesData, PutFamiliesResponses } from './types.gen';
