// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * A Family
 */
export type Family = {
    /**
     * unique ID identifying
     * a family
     *
     */
    reference: string;
    /**
     * relationship to the head of family
     */
    relationship: 'self' | 'spouse' | 'child' | 'relatives';
    name: string;
    birthDate: string;
    /**
     * Family's job
     */
    job: {
        name: string;
    };
    /**
     * Array of possessions
     */
    have: Array<{
        reference: string;
        name: string;
    }>;
};

/**
 * Income
 */
export type Income = {
    reference: string;
    familyId: string;
    source: string;
    amount: number;
};

export type GetFamiliesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * A family's name, reference or
         * partial description
         *
         */
        'free-query'?: string;
    };
    url: '/families';
};

export type GetFamiliesResponses = {
    /**
     * Array of Family
     */
    200: Array<Family>;
};

export type GetFamiliesResponse = GetFamiliesResponses[keyof GetFamiliesResponses];

export type PostFamiliesData = {
    /**
     * Family's information
     */
    body?: Family;
    path?: never;
    query?: never;
    url: '/families';
};

export type PostFamiliesResponses = {
    /**
     * Family added
     *
     */
    200: unknown;
};

export type PutFamiliesData = {
    /**
     * Array of Family
     */
    body?: Array<Family>;
    path?: never;
    query?: never;
    url: '/families';
};

export type PutFamiliesResponses = {
    /**
     * Family edited
     *
     */
    200: unknown;
};

export type GetIncomData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/incom';
};

export type GetIncomResponses = {
    /**
     * Array of Income
     */
    200: Array<Income>;
};

export type GetIncomResponse = GetIncomResponses[keyof GetIncomResponses];

export type PostIncomData = {
    /**
     * Income's information
     */
    body?: Income;
    path?: never;
    query?: never;
    url: '/incom';
};

export type PostIncomResponses = {
    /**
     * Income added
     *
     */
    200: unknown;
};
