openapi: "3.0.0"
info:
  title: Shopping API
  version: "1.0"

tags:
  - name: Family
    description: Families Operation
  - name: Income
    description: Income Operation

components:
  schemas:
    Family:
      type: object
      description: A Family
      required:
        - reference
        - relationship
        - name
        - birthDate
        - job
        - have
      properties:
        reference:
          description: |
            unique ID identifying
            a family
          type: string
        relationship:
          type: string
          enum:
            - self
            - spouse
            - child
            - relatives
          description: relationship to the head of family
        name:
          type: string
        birthDate:
          type: string
          format: date
        job:
          type: object
          description: Family's job
          required:
            - name
          properties:
            name:
              type: string
        have:
          type: array
          description: Array of possessions
          items:
            type: object
            description: A possession
            required:
              - reference
              - name
            properties:
              reference:
                type: string
              name:
                type: string
    Income:
      type: object
      description: Income
      required:
        - reference
        - familyId
        - source
        - amount
      properties:
        reference:
          type: string
        familyId:
          type: string
        source:
          type: string
        amount:
          type: number
paths:
  /families:
    description: The families catalog
    get:
      summary: Search families
      tags:
        - Family
      description: |
        Search families
        using a free query parameter
      parameters:
        - name: free-query
          description: |
            A family's name, reference or
            partial description
          in: query
          schema:
            type: string
      responses:
        "200":
          description: Families matching free query
          content:
            application/json:
              schema:
                type: array
                description: Array of Family
                items:
                  $ref: "#/components/schemas/Family"
    post:
      summary: Add family
      description: |
        Add family's parameter
      tags:
        - Family
      requestBody:
        description: Family's information
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Family"
      responses:
        "200":
          description: |
            Family added
    put:
      summary: Add family
      description: |
        Add family's parameter
      tags:
        - Family
      requestBody:
        description: Family's information
        content:
          application/json:
            schema:
                type: array
                description: Array of Family
                items:
                  $ref: "#/components/schemas/Family"
      responses:
        "200":
          description: |
            Family edited
  /incom:
    description: The income catalog
    get:
      summary: Get incomes
      description: |
        Get all incomes
      tags:
        - Income
      responses:
        "200":
          description: Income
          content:
            application/json:
              schema:
                type: array
                description: Array of Income
                items:
                  $ref: "#/components/schemas/Income"
    post:
      summary: Add income
      description: |
        Add income's parameter
      tags:
        - Income
      requestBody:
        description: Income's information
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Income"
      responses:
        "200":
          description: |
            Income added