/* tslint:disable */
/* eslint-disable */
/**
 * Shopping API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Family's job
 * @export
 * @interface FamilyJob
 */
export interface FamilyJob {
    /**
     * 
     * @type {string}
     * @memberof FamilyJob
     */
    name: string;
}

/**
 * Check if a given object implements the FamilyJob interface.
 */
export function instanceOfFamilyJob(value: object): value is FamilyJob {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function FamilyJobFromJSON(json: any): FamilyJob {
    return FamilyJobFromJSONTyped(json, false);
}

export function FamilyJobFromJSONTyped(json: any, ignoreDiscriminator: boolean): FamilyJob {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
    };
}

export function FamilyJobToJSON(json: any): FamilyJob {
    return FamilyJobToJSONTyped(json, false);
}

export function FamilyJobToJSONTyped(value?: FamilyJob | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
    };
}

