/* tslint:disable */
/* eslint-disable */
/**
 * Shopping API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * A possession
 * @export
 * @interface FamilyHaveInner
 */
export interface FamilyHaveInner {
    /**
     * 
     * @type {string}
     * @memberof FamilyHaveInner
     */
    reference: string;
    /**
     * 
     * @type {string}
     * @memberof FamilyHaveInner
     */
    name: string;
}

/**
 * Check if a given object implements the FamilyHaveInner interface.
 */
export function instanceOfFamilyHaveInner(value: object): value is FamilyHaveInner {
    if (!('reference' in value) || value['reference'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function FamilyHaveInnerFromJSON(json: any): FamilyHaveInner {
    return FamilyHaveInnerFromJSONTyped(json, false);
}

export function FamilyHaveInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): FamilyHaveInner {
    if (json == null) {
        return json;
    }
    return {
        
        'reference': json['reference'],
        'name': json['name'],
    };
}

export function FamilyHaveInnerToJSON(json: any): FamilyHaveInner {
    return FamilyHaveInnerToJSONTyped(json, false);
}

export function FamilyHaveInnerToJSONTyped(value?: FamilyHaveInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'reference': value['reference'],
        'name': value['name'],
    };
}

