/* tslint:disable */
/* eslint-disable */
/**
 * Shopping API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FamilyHaveInner } from './FamilyHaveInner';
import {
    FamilyHaveInnerFromJSON,
    FamilyHaveInnerFromJSONTyped,
    FamilyHaveInnerToJSON,
    FamilyHaveInnerToJSONTyped,
} from './FamilyHaveInner';
import type { FamilyJob } from './FamilyJob';
import {
    FamilyJobFromJSON,
    FamilyJobFromJSONTyped,
    FamilyJobToJSON,
    FamilyJobToJSONTyped,
} from './FamilyJob';

/**
 * A Family
 * @export
 * @interface Family
 */
export interface Family {
    /**
     * unique ID identifying
     * a family
     * 
     * @type {string}
     * @memberof Family
     */
    reference: string;
    /**
     * relationship to the head of family
     * @type {string}
     * @memberof Family
     */
    relationship: FamilyRelationshipEnum;
    /**
     * 
     * @type {string}
     * @memberof Family
     */
    name: string;
    /**
     * 
     * @type {Date}
     * @memberof Family
     */
    birthDate: Date;
    /**
     * 
     * @type {FamilyJob}
     * @memberof Family
     */
    job: FamilyJob;
    /**
     * Array of possessions
     * @type {Array<FamilyHaveInner>}
     * @memberof Family
     */
    have: Array<FamilyHaveInner>;
}


/**
 * @export
 */
export const FamilyRelationshipEnum = {
    Self: 'self',
    Spouse: 'spouse',
    Child: 'child',
    Relatives: 'relatives'
} as const;
export type FamilyRelationshipEnum = typeof FamilyRelationshipEnum[keyof typeof FamilyRelationshipEnum];


/**
 * Check if a given object implements the Family interface.
 */
export function instanceOfFamily(value: object): value is Family {
    if (!('reference' in value) || value['reference'] === undefined) return false;
    if (!('relationship' in value) || value['relationship'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('birthDate' in value) || value['birthDate'] === undefined) return false;
    if (!('job' in value) || value['job'] === undefined) return false;
    if (!('have' in value) || value['have'] === undefined) return false;
    return true;
}

export function FamilyFromJSON(json: any): Family {
    return FamilyFromJSONTyped(json, false);
}

export function FamilyFromJSONTyped(json: any, ignoreDiscriminator: boolean): Family {
    if (json == null) {
        return json;
    }
    return {
        
        'reference': json['reference'],
        'relationship': json['relationship'],
        'name': json['name'],
        'birthDate': (new Date(json['birthDate'])),
        'job': FamilyJobFromJSON(json['job']),
        'have': ((json['have'] as Array<any>).map(FamilyHaveInnerFromJSON)),
    };
}

export function FamilyToJSON(json: any): Family {
    return FamilyToJSONTyped(json, false);
}

export function FamilyToJSONTyped(value?: Family | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'reference': value['reference'],
        'relationship': value['relationship'],
        'name': value['name'],
        'birthDate': value['birthDate'].toISOString().substring(0,10),
        'job': FamilyJobToJSON(value['job']),
        'have': ((value['have'] as Array<any>).map(FamilyHaveInnerToJSON)),
    };
}

