/* tslint:disable */
/* eslint-disable */
/**
 * Shopping API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Income
 * @export
 * @interface Income
 */
export interface Income {
    /**
     * 
     * @type {string}
     * @memberof Income
     */
    reference: string;
    /**
     * 
     * @type {string}
     * @memberof Income
     */
    familyId: string;
    /**
     * 
     * @type {string}
     * @memberof Income
     */
    source: string;
    /**
     * 
     * @type {number}
     * @memberof Income
     */
    amount: number;
}

/**
 * Check if a given object implements the Income interface.
 */
export function instanceOfIncome(value: object): value is Income {
    if (!('reference' in value) || value['reference'] === undefined) return false;
    if (!('familyId' in value) || value['familyId'] === undefined) return false;
    if (!('source' in value) || value['source'] === undefined) return false;
    if (!('amount' in value) || value['amount'] === undefined) return false;
    return true;
}

export function IncomeFromJSON(json: any): Income {
    return IncomeFromJSONTyped(json, false);
}

export function IncomeFromJSONTyped(json: any, ignoreDiscriminator: boolean): Income {
    if (json == null) {
        return json;
    }
    return {
        
        'reference': json['reference'],
        'familyId': json['familyId'],
        'source': json['source'],
        'amount': json['amount'],
    };
}

export function IncomeToJSON(json: any): Income {
    return IncomeToJSONTyped(json, false);
}

export function IncomeToJSONTyped(value?: Income | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'reference': value['reference'],
        'familyId': value['familyId'],
        'source': value['source'],
        'amount': value['amount'],
    };
}

